"""add payroll

Revision ID: 505b99742591
Revises: 7686303663d3
Create Date: 2026-07-03 11:00:15.738522
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '505b99742591'
down_revision: Union[str, None] = '7686303663d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('basic', sa.Integer(), nullable=False),
    sa.Column('hra', sa.Integer(), nullable=False),
    sa.Column('allowances', sa.Integer(), nullable=False),
    sa.Column('deductions', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Integer(), nullable=False),
    sa.Column('net', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('draft', 'released', name='payslip_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', name='uq_payslip_user_month')
    )
    op.create_index(op.f('ix_payslips_company_id'), 'payslips', ['company_id'], unique=False)
    op.create_index(op.f('ix_payslips_status'), 'payslips', ['status'], unique=False)
    op.create_index(op.f('ix_payslips_user_id'), 'payslips', ['user_id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('basic', sa.Integer(), nullable=False),
    sa.Column('hra', sa.Integer(), nullable=False),
    sa.Column('allowances', sa.Integer(), nullable=False),
    sa.Column('deductions', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_salary_structures_company_id'), 'salary_structures', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_structures_company_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_payslips_user_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_status'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_company_id'), table_name='payslips')
    op.drop_table('payslips')
    # ### end Alembic commands ###
