"""add leaves_used to users

Revision ID: 51bc67c5ee1e
Revises: e4fbc77b3fcd
Create Date: 2026-07-01 11:32:54.595537
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51bc67c5ee1e'
down_revision: Union[str, None] = 'e4fbc77b3fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('leaves_used', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'leaves_used')
    # ### end Alembic commands ###
